export const subjects: string[] = [
    "Academic English Program-Int'l (AEPI)",
    "Academic Inquiry & Scholarship (AIS)",
    "Accounting (ACC)",
    "Adult and Higher Education (AHE)",
    "Adult Learning and Teaching (ALT)",
    "Aerospace Studies (ASC)",
    "Affiliated Studies (AFS)",
    "African American Studies (AAS)",
    "Agriculture/Environmental Hort (AGEH)",
    "Allied Health Sciences (AHS)",
    "Alternative Bilingual (ABL)",
    "American Sign Language (ASL)",
    "American Studies (AMS)",
    "Anthropology (ANT)",
    "App Design & Behavior Resource (ADBR)",
    "Applied-Industrial Mathematics (AIM)",
    "Arabic (ARA)",
    "Architecture (ARC)",
    "Art (ART)",
    "Art History and Criticism (AHC)",
    "Astronomy (AST)",
    "Bicultural Bilingual Studies (BBL)",
    "Biochemistry (BCH)",
    "Biology (BIO)",
    "Biomedical Engineering (BME)",
    "Business Law (BLW)",
    "Business of Health (BOH)",
    "Business Scholars Program (BSP)",
    "Chemical Engineering (CME)",
    "Chemistry (CHE)",
    "Chinese (CHN)",
    "Civil Engineering (CE)",
    "Classics (CLA)",
    "College of Arch-Foundations (COA)",
    "College Success Seminar (CSS)",
    "Communication (COM)",
    "Comparative Studies-Humanities (CSH)",
    "Computer Engineering (CPE)",
    "Computer Science (CS)",
    "Construction Sci and Management (CSM)",
    "Core Curriculum (COR)",
    "Counseling (COU)",
    "Criminal Justice (CRJ)",
    "Curriculum and Instruction (CI)",
    "Curriculum and Instruction (C&I)",
    "Dance (DAN)",
    "Data Analytics (DA)",
    "Data Science (DS)",
    "Demography (DEM)",
    "Differential Equations (DIF)",
    "DOD Cyber Scholarship Program (CYSP)",
    "Early Childhood (ECE)",
    "Earth and Environmental Science (EES)",
    "Economics (ECO)",
    "Education (EDU)",
    "Education & Human Development (EHD)",
    "Educational Leadership (EDL)",
    "Educational Psychology (EDP)",
    "Electrical Engineering (EE)",
    "Engineering (EGR)",
    "Engineering/Integrated Design (EID)",
    "English (ENG)",
    "English as a Second Language (ESL)",
    "English for Interntl Students (EIS)",
    "Entrepreneurship (ENT)",
    "Environmental Sciences (ES)",
    "Equity and Education (EED)",
    "Facility and Property Management (FM)",
    "FIN Assessment Competency Test (FACT)",
    "Finance (FIN)",
    "Foreign Languages (FL)",
    "French (FRN)",
    "General Business Admin (GBA)",
    "Genratng Edu Excel in Math and Sci (GEM)",
    "Geography (GRG)",
    "Geography & Env Sustainability (GES)",
    "Geology (GEO)",
    "German (GER)",
    "Global Affairs (GLA)",
    "Graduate Pathway (GPWY)",
    "Graduate Stdnt Learning Assist (GSL)",
    "Greek (GRK)",
    "Health (HTH)",
    "Health, Community and Policy (HCP)",
    "Higher Ed Stdnt Affairs Admin (HSA)",
    "History (HIS)",
    "Honors (HON)",
    "Human Neuroscience (HNSC)",
    "Humanities (HUM)",
    "Information Systems (IS)",
    "Instructional Leadership (ILR)",
    "Instructional Technology (IST)",
    "Intensive English Camp (IEC)",
    "Intensive English Program (IEP)",
    "Interdisciplinary Learn Teach (ILT)",
    "Interdisciplinary Studies (IDS)",
    "Interior Design (IDE)",
    "International Research/Study (IRS)",
    "International Studies (INS)",
    "Italian (ITL)",
    "Japanese (JPN)",
    "Kinesiology (KIN)",
    "Kinesiology and Health (KAH)",
    "Korean (KOR)",
    "Latin (LAT)",
    "Latin American Studies (LAS)",
    "Leadership (LDR)",
    "Learning Communities (LC)",
    "Learning, Design & Technology (LDT)",
    "Legal Studies (LGS)",
    "Liberal and Fine Arts (LFA)",
    "Linguistics (LNG)",
    "Literacy Education (LTED)",
    "Management (MGT)",
    "Management of Technology (MOT)",
    "Management Science (MS)",
    "Marketing (MKT)",
    "Master of Business Admin (MBA)",
    "Materials Engineering (MATE)",
    "Mathematics (MAT)",
    "Mathematics (MTC)",
    "Mathematics of Data and Comput (MDC)",
    "Mechanical Engineering (ME)",
    "Media Studies (MES)",
    "Medical Humanities (MHU)",
    "Mexican American Studies (MAS)",
    "Military Science (MSC)",
    "Molecular Microbiology & Immunology (MMI)",
    "Multidisciplinary Studies (MDS)",
    "Museum Studies (MSM)",
    "Music (MUS)",
    "National Security (NS)",
    "National Student Exchange (NXC)",
    "Neuroscience/Dev & Regen Bio (NDRB)",
    "Non-course Based Instruction (NCB)",
    "Non-profit Management (NPO)",
    "Non-Provisioned Course for BB (NPC)",
    "Nutrition (NTR)",
    "Nutrition and Dietetics (NDT)",
    "NWVista Developmental Math (NWM)",
    "Paralegal Certificate Program (PLGL)",
    "Philosophy (PHI)",
    "Physics (PHY)",
    "Political Science (POL)",
    "Politics and Law (PAL)",
    "Psychology (PSY)",
    "Public Administration (PAD)",
    "Public Health (PUB)",
    "QLP Exemption (Q) (QLE)",
    "QLP Workshop (Q) (QLW)",
    "Race, Ethn, Gender & Sexuality (REGS)",
    "Reading (RDG)",
    "Real Estate (RFD)",
    "Russian (RUS)",
    "Sciences (SCI)",
    "Secondary Education (SED)",
    "Social Work (SWK)",
    "Sociology (SOC)",
    "Spanish (SPN)",
    "Special Education (SPE)",
    "Sport, Event and Tourism Management (SET)",
    "Statistics (STA)",
    "Strategic Stds & Def Analysis (SSDA)",
    "Theater (THR)",
    "Top Scholar Program (TSP)",
    "Tramsfer Subject (UHC)",
    "Tranfer Subject (WLLC)",
    "Transfer Subect (EIO)",
    "Transfer Subject (ELAD)",
    "Transfer Subject (EHON)",
    "Transfer Subject (ENTB)",
    "Transfer Subject (ENVA)",
    "Transfer Subject (EPIB)",
    "Transfer Subject (ENGY)",
    "Transfer Subject (ENQ)",
    "Transfer Subject (ENSY)",
    "Transfer Subject (FANR)",
    "Transfer Subject (FAP)",
    "Transfer Subject (FATH)",
    "Transfer Subject (FAU)",
    "Transfer Subject (FAVS)",
    "Transfer Subject (FB)",
    "Transfer Subject (FHGE)",
    "Transfer Subject (FIBR)",
    "Transfer Subject (ESMS)",
    "Transfer Subject (ESW)",
    "Transfer Subject (ETCS)",
    "Transfer Subject (ETDD)",
    "Transfer Subject (ETE)",
    "Transfer Subject (ETEE)",
    "Transfer Subject (ETHM)",
    "Transfer Subject (ETLW)",
    "Transfer Subject (ETP)",
    "Transfer Subject (EVEG)",
    "Transfer Subject (EWB)",
    "Transfer Subject (EECT)",
    "Transfer Subject (EGDT)",
    "Transfer Subject (EDML)",
    "Transfer Subject (ECIS)",
    "Transfer Subject (DDHS)",
    "Transfer Subject (DEC)",
    "Transfer Subject (EACH)",
    "Transfer Subject (EAPS)",
    "Transfer Subject (EATM)",
    "Transfer Subject (EBME)",
    "Transfer Subject (ECCE)",
    "Transfer Subject (DIP)",
    "Transfer Subject (DMER)",
    "Transfer Subject (DMTS)",
    "Transfer Subject (DSA)",
    "Transfer subject (DST)",
    "Transfer Subject (DSTA)",
    "Transfer Subject (DTR)",
    "Transfer Subject (DESM)",
    "Transfer Subject (DF)",
    "Transfer Subject (DFHH)",
    "Transfer Subject (DGAD)",
    "Transfer Subject (DGL)",
    "Transfer Subject (DIAA)",
    "Transfer Subject (DIAM)",
    "Transfer Subject (IDP)",
    "Transfer Subject (HSDA)",
    "Transfer Subject (HSVC)",
    "Transfer Subject (IERT)",
    "Transfer Subject (IFMG)",
    "Transfer Subject (HUNF)",
    "Transfer Subject (HUST)",
    "Transfer Subject (ICST)",
    "Transfer Subject (ICT)",
    "Transfer Subject (HPAS)",
    "Transfer Subject (HPHM)",
    "Transfer Subject (HPLW)",
    "Transfer Subject (HPTC)",
    "Transfer Subject (HIWD)",
    "Transfer Subject (HKIN)",
    "Transfer Subject (HMSV)",
    "Transfer Subject (HND)",
    "Transfer Subject (GRAR)",
    "Transfer Subject (ELCT)",
    "Transfer Subject (HIMA)",
    "Transfer Subject (HD&E)",
    "Transfer Subject (HEDP)",
    "Transfer Subject (HEPD)",
    "Transfer Subject (HESS)",
    "Transfer Subject (GSSS)",
    "Transfer Subject (HABS)",
    "Transfer Subject (HAPP)",
    "Transfer Subject (HASL)",
    "Transfer Subject (HCD)",
    "Transfer Subject (GRKC)",
    "Transfer Subject (GSCO)",
    "Transfer Subject (GLOS)",
    "Transfer Subject (GMUS)",
    "Transfer Subject (GNE)",
    "Transfer Subject (GEGN)",
    "Transfer Subject (GGEO)",
    "Transfer Subject (GKM)",
    "Transfer Subject (GKT)",
    "Transfer Subject (FS-N)",
    "Transfer Subject (FSHV)",
    "Transfer Subject (FYHI)",
    "Transfer Subject (FYOS)",
    "Transfer Subject (FYSW)",
    "Transfer Subject (FYWS)",
    "Transfer Subject (G&R)",
    "Transfer Subject (GAMS)",
    "Transfer Subject (FLKH)",
    "Transfer Subject (FMX)",
    "Transfer Subject (FINH)",
    "Transfer Subject (ESEM)",
    "Transfer Subject (ESHE)",
    "Transfer Subject (CSNE)",
    "Transfer Subject (CSUY)",
    "Transfer Subject (CURI)",
    "Transfer Subject (CUSC)",
    "Transfer Subject (CWP)",
    "Transfer Subject (CYB)",
    "Transfer Subject (CYBD)",
    "Transfer Subject (CRWR)",
    "Transfer Subject (CPEA)",
    "Transfer Subject (CSDS)",
    "Transfer Subject (CSJS)",
    "Transfer Subject (CIEE)",
    "Transfer Subject (CIIN)",
    "Transfer Subject (CIMA)",
    "Transfer Subject (CISN)",
    "Transfer Subject (CMG)",
    "Transfer Subject (CMNS)",
    "Transfer Subject (CNP)",
    "Transfer Subject (CNTK)",
    "Transfer Subject (COSA)",
    "Transfer Subject (COSP)",
    "Transfer Subject (COCA)",
    "Transfer Subject (CHSE)",
    "Transfer Subject (CHTH)",
    "Transfer Subject (CABT)",
    "Transfer Subject (CAMX)",
    "Transfer Subject (CARS)",
    "Transfer Subject (BSPH)",
    "Transfer Subject (BTT)",
    "Transfer Subject (BUS&)",
    "Transfer Subject (BPT)",
    "Transfer Subject (BQC)",
    "Transfer Subject (BQT)",
    "Transfer Subject (BRIT)",
    "Transfer Subject (BSIS)",
    "Transfer Subject (ASEM)",
    "Transfer Subject (CLD)",
    "Transfer Subject (CLEN)",
    "Transfer Subject (CLM)",
    "Transfer Subject (CLSM)",
    "Transfer Subject (CLTR)",
    "Transfer Subject (CLWR)",
    "Transfer Subject (CMAS)",
    "Transfer Subject (CELR)",
    "Transfer Subject (CEPY)",
    "Transfer Subject (CGSA)",
    "Transfer Subject (CGSC)",
    "Transfer Subject (CHLH)",
    "Transfer Subject (BNAL)",
    "Transfer Subject (BIR)",
    "Transfer Subject (BISS)",
    "Transfer Subject (BIZ)",
    "Transfer Subject (BDJ)",
    "Transfer Subject (BEAR)",
    "Transfer Subject (BFOM)",
    "Transfer Subject (ATCM)",
    "Transfer Subject (AVTN)",
    "Transfer Subject (AWR)",
    "Transfer Subject (AWSC)",
    "Transfer Subject (BAMK)",
    "Transfer Subject (BAP)",
    "Transfer Subject (BASV)",
    "Transfer Subject (AREA)",
    "Transfer Subject (ARIN)",
    "Transfer Subject (AROU)",
    "Transfer Subject (APFS)",
    "Transfer Subject (APLE)",
    "Transfer Subject (AMAE)",
    "Transfer Subject (AHMX)",
    "Transfer Subject (AMUN)",
    "Transfer Subject (AMUY)",
    "Transfer Subject (ANC)",
    "Transfer Subject (ACCG)",
    "Transfer Subject (AGCM)",
    "Transfer Subject (AGCR)",
    "Transfer Subject (ADEN)",
    "Transfer Subject (ADI)",
    "Transfer Subject (ADMK)",
    "Transfer Subject (ADOT)",
    "Transfer Subject (ADPS)",
    "Transfer Subject (ABT)",
    "Transfer Subject (AASC)",
    "Transfer Subject (ABF)",
    "Transfer Subject (027)",
    "Transfer Subject (0805)",
    "Transfer Subject (0813)",
    "Transfer Subject (0891)",
    "Transfer Subject (131)",
    "Transfer Subject (135)",
    "Transfer Subject (169)",
    "Transfer Subject (20E)",
    "Transfer Subject (3001)",
    "Transfer Subject (3981)",
    "Transfer Subject (3DSC)",
    "Transfer Subject (3DTD)",
    "Transfer Subject (563)",
    "Transfer Subject (565)",
    "Transfer Subject (567)",
    "Transfer Subject (575)",
    "Transfer Subject (606)",
    "Transfer Subject (614)",
    "Transfer Subject (6200)",
    "Transfer Subject (704)",
    "Transfer Subject (WRSP)",
    "Transfer Subject (WSTU)",
    "Transfer Subject (WSU)",
    "Transfer Subject (WSUE)",
    "Transfer Subject (XCOM)",
    "Transfer Subject (YMN)",
    "Transfer Subject (YORB)",
    "Transfer Subject (ZSPN)",
    "Transfer Subject (UDHS)",
    "Transfer Subject (UIP)",
    "Transfer Subject (UIST)",
    "Transfer Subject (UMYO)",
    "Transfer Subject (UNAS)",
    "Transfer Subject (UNCS)",
    "Transfer Subject (UNIC)",
    "Transfer Subject (UNSC)",
    "Transfer Subject (SSWI)",
    "Transfer Subject (STCO)",
    "Transfer Subject (STRT)",
    "Transfer Subject (STSU)",
    "Transfer Subject (SUST)",
    "Transfer Subject (UCJ)",
    "Transfer Subject (USAF)",
    "Transfer Subject (TLIM)",
    "Transfer Subject (TLSE)",
    "Transfer Subject (TOIN)",
    "Transfer Subject (TRNF)",
    "Transfer Subject (UWW)",
    "Transfer Subject (VIE)",
    "Transfer Subject (VSM)",
    "Transfer Subject (VSO)",
    "Transfer Subject (VTRB)",
    "Transfer Subject (VX)",
    "Transfer Subject (WCSC)",
    "Transfer Subject (WCWP)",
    "Transfer Subject (WDD)",
    "Transfer Subject (WFIT)",
    "Transfer Subject (WG)",
    "Transfer Subject (SFS)",
    "Transfer Subject (SGD)",
    "Transfer Subject (SHPS)",
    "Transfer Subject (SIB)",
    "Transfer Subject (SLC)",
    "Transfer Subject (SLPA)",
    "Transfer Subject (SLSS)",
    "Transfer Subject (SMFG)",
    "Transfer Subject (SNC)",
    "Transfer Subject (SOET)",
    "Transfer Subject (SOJU)",
    "Transfer Subject (SPCS)",
    "Transfer Subject (SAHE)",
    "Transfer Subject (SCHM)",
    "Transfer Subject (REES)",
    "Transfer Subject (SPEX)",
    "Transfer Subject (SPHL)",
    "Transfer Subject (SPME)",
    "Transfer Subject (SPWR)",
    "Transfer Subject (SRSE)",
    "Transfer Subject (SDC)",
    "Transfer Subject (SYGA)",
    "Transfer Subject (SYSC)",
    "Transfer Subject (TAFI)",
    "Transfer Subject (TCN)",
    "Transfer Subject (TCT)",
    "Transfer Subject (TDIN)",
    "Transfer Subject (TDT)",
    "Transfer Subject (TELV)",
    "Transfer Subject (TGLG)",
    "Transfer Subject (THG)",
    "Transfer Subject (RHW)",
    "Transfer Subject (RLTH)",
    "Transfer Subject (RNC)",
    "Transfer Subject (RPTR)",
    "Transfer Subject (QMP)",
    "Transfer Subject (RBTC)",
    "Transfer Subject (PVEX)",
    "Transfer Subject (PYDI)",
    "Transfer Subject (QHW)",
    "Transfer Subject (PRW)",
    "Transfer Subject (PSN)",
    "Transfer Subject (NUFD)",
    "Transfer Subject (PLN)",
    "Transfer Subject (PLRU)",
    "Transfer Subject (PNNY)",
    "Transfer Subject (PNUR)",
    "Transfer Subject (PAMU)",
    "Transfer Subject (PATB)",
    "Transfer Subject (PBRL)",
    "Transfer Subject (PDEN)",
    "Transfer Subject (PDHU)",
    "Transfer Subject (PEY)",
    "Transfer Subject (PGMT)",
    "Transfer Subject (PHBR)",
    "Transfer Subject (PHEH)",
    "Transfer Subject (NEP)",
    "Transfer Subject (NMA)",
    "Transfer Subject (NMC)",
    "Transfer Subject (NMIX)",
    "Transfer Subject (NSP)",
    "Transfer Subject (OCRE)",
    "Transfer Subject (OCTA)",
    "Transfer Subject (OFFP)",
    "Transfer Subject (OFFR)",
    "Transfer Subject (OFM)",
    "Transfer Subject (OGL)",
    "Transfer Subject (OILS)",
    "Transfer Subject (ORCM)",
    "Transfer Subject (OSHT)",
    "Transfer Subject (OU)",
    "Transfer Subject (PACT)",
    "Transfer Subject (MUTG)",
    "Transfer Subject (NASE)",
    "Transfer Subject (MTSE)",
    "Transfer Subject (MUCA)",
    "Transfer Subject (MUJ)",
    "Transfer Subject (MURP)",
    "Transfer Subject (MMST)",
    "Transfer Subject (MPFV)",
    "Transfer Subject (MPPH)",
    "Transfer Subject (MPSM)",
    "Transfer Subject (MPT)",
    "Transfer Subject (MATA)",
    "Transfer Subject (LTLA)",
    "Transfer Subject (LWA)",
    "Transfer Subject (MAAA)",
    "Transfer Subject (MAM)",
    "Transfer Subject (LSED)",
    "Transfer Subject (LSJ)",
    "Transfer Subject (LGBT)",
    "Transfer Subject (LIBB)",
    "Transfer Subject (LIBY)",
    "Transfer Subject (LLAT)",
    "Transfer Subject (LLL)",
    "Transfer Subject (MIEH)",
    "Transfer Subject (MLSL)",
    "Transfer Subject (MLSP)",
    "Transfer Subject (MFA)",
    "Transfer Subject (MGTO)",
    "Transfer Subject (MDP)",
    "Transfer Subject (MAUY)",
    "Transfer Subject (MCA)",
    "Transfer Subject (MCAD)",
    "Transfer Subject (MCBC)",
    "Transfer Subject (LEIN)",
    "Transfer Subject (KRS)",
    "Transfer Subject (LABR)",
    "Transfer Subject (LAD)",
    "Transfer Subject (KATH)",
    "Transfer Subject (KINP)",
    "Transfer Subject (KNSF)",
    "Transfer Subject (JRLC)",
    "Transfer Subject (JRNA)",
    "Transfer Subject (JSLA)",
    "Transfer Subject (JWLR)",
    "Transfer Subject (ITOP)",
    "Transfer Subject (ITWD)",
    "Transfer Subject (JMP)",
    "Transfer Subject (IRST)",
    "Transfer Subject (ITAS)",
    "Transfer Subject (IPEC)",
    "Transfer Subject (IN4M)",
    "Transfer Subject (INFV)",
    "Transfer Subject (INQS)",
    "Transfer Subject (INRE)",
    "Transfer Subject (INRW)",
    "Transfer Subjeect (ELCR)",
    "Transfer Subjet (IGST)",
    "Transfer Suject (DTT)",
    "Transfet Subject (HHPA)",
    "Translation & Interpreting St (TIS)",
    "Translational Science (TRSC)",
    "Trasfer Subject (NWIT)",
    "University College Studies (UCS)",
    "University Peer Mentorship (UPM)",
    "Urban and Regional Planning (URP)",
    "UTeach (UTE)",
    "Women and Gender Studies (WGS)",
    "Women, Gender & Sexuality St (WGSS)",
    "Womens Studies (WS)",
    "Writing Program (WRC)"
];
